[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd web && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd web && npm run build"]

[start]
cmd = "cd web && npm run start"

[variables]
NODE_ENV = "production"
PORT = "4000"
